spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookingdb
kafka:
  server: localhost:9092
  topic:
    availabilitysearch: hotel_availability_searches
  consumer:
    groupId: booking